base_url = ""
compile_sass = true
title = "Radio"
description = "A minimalist portfolio theme"

[extra]
radio_logo = ""
radio_nav_links = [
    {url = "https://github.com/krisradio/zola-radio", name = "GitHub"},
]
section_col = 3